relaychain:
  image: p1k1m4n/polkadot-fast-runtime:1.1.0-6
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env:
    RUST_LOG: info
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob

parachains:
  - image: mangatasolutions/mangata-node:rc-0.32.1
    chain:
      base: mangata-kusama-local
      collators:
        - alice
        - bob
      sudo: alice
      skipCollatorSelection: true
      skipBalances: true
    id: 2110
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      # RUST_LOG: info,block_builder=trace,block_shuffler=trace,runtime::ver=trace,txpool=trace,rpc::nonce=trace
      RUST_LOG: info,migration=debug
    volumePath: /mangata/data
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
